export const TEST_TYPE = "test_type";
export const UPDATE_LATEST_USER_POSITION = "update_latest_user_position";
export const POSITION_QUERYING_STATUS = "position_querying_started";
export const ZONES_FETCHED_SUCCESS = "zones_fetched_success";
export const NEW_NOTIFICATION_RECEIVED = "new_notification_received";
export const ADD_NEW_ITEM_OLD_NOTIFICATION = "add_new_item_old_notification";
export const FORCAST_FETCHED_SUCCESS = 'forcasr_fetched_success';
export const NEW_FCM_TOKEN = "new_fcm_token";

export const CLEAR_LANGUAGE = "CLEAR_LANGUAGE";
export const SET_LANGUAGE = "SET_LANGUAGE";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_ACTIVITY_LOG = "UPDATE_ACTIVITY_LOG";
export const SET_ACTIVITY_LOG = "SET_ACTIVITY_LOG";
export const CLEAR_ACTIVITY_LOG = "CLEAR_ACTIVITY_LOG";
export const ACTIVITY_LOG_BACKEND_UPDATED = "ACTIVITY_LOG_BACKEND_UPDATED";
export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE";
export const USRE_PROFILE_BACKEND_UPDATED = "USRE_PROFILE_BACKEND_UPDATED";

export const SET_ALERT_LIST = "SET_ALERT_LIST";
export const CLEAR_ALERT_LIST = "CLEAR_ALERT_LIST";
export const ADD_NEW_ALERT = "ADD_NEW_ALERT";
export const IS_PUSH_CONFIGURED = "IS_PUSH_CONFIGURED";

export const CLEAR_ROUTE_REDUCER = "CLEAR_ROUTE_REDUCER";
export const SET_POINTS_LIST = "SET_POINTS_LIST";
export const ADD_POINT = "ADD_POINT";
export const POINT_BACKEND_UPDATED = "POINT_BACKEND_UPDATED";
export const SET_ROUTES_LIST = "SET_ROUTES_LIST";
export const ADD_ROUTE = "ADD_ROUTE";
export const ROUTE_BACKEND_UPDATED = "ROUTE_BACKEND_UPDATED";
export const SET_CURRENT_USER_LOCATION = "SET_CURRENT_USER_LOCATION";
export const CLEAR_TEMP_LOCATION = "CLEAR_TEMP_LOCATION";
export const ADD_TEMP_LOCATION = "ADD_TEMP_LOCATION";
export const GEOFENCE_STATUS_IN = "GEOFENCE_STATUS_IN";
export const GEOFENCE_STATUS_OUT = "GEOFENCE_STATUS_OUT";
export const GEOFENCE_STATUS_WARNING_SHOWED = "GEOFENCE_STATUS_WARNING_SHOWED";

export const SET_DOF_SLIDER_IMAGES = "SET_DOF_SLIDER_IMAGES";
export const SET_DOF_BUTTON_LINKS = "SET_DOF_BUTTON_LINKS";
export const SET_DOF_WEBVIEW_URL = "SET_DOF_WEBVIEW_URL";
export const CLEAR_DOF_REDUCER = "CLEAR_DOF_REDUCER";
export const SET_DOF_DATA = "SET_DOF_DATA";

export const SET_TODAY_WEATHER = "SET_TODAY_WEATHER";
export const SET_OTHER_ZONES_WEATHER = "SET_OTHER_ZONES_WEATHER";
export const CLEAR_WEATHER_DATA = "CLEAR_WEATHER_DATA";
export const SET_WEATHER_DATA = "SET_WEATHER_DATA";

export const UPDATE_FIRST_TIME_USER_FLAG = "UPDATE_FIRST_TIME_USER_FLAG";
export const USER_LOG_OUT = "USER_LOG_OUT";
export const USER_LOG_IN = "USER_LOG_IN";

export const IS_INTERNET_CONNECTED = "IS_INTERNET_CONNECTED";
export const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION";
export const UPDATE_TRIAL_ACCOUNT_INFO = "UPDATE_TRIAL_ACCOUNT_INFO";

export const SET_ZONES = "SET_ZONES";




